fix: deps on delete
Fix the following error when destroying

```
Error: Error, failed to deleteuser
spacelift-backend@self-hosted-v3-testing.iam in instance
spacelift-e03ef1c2: googleapi: Error 400: Invalid request: failed to
delete user spacelift-backend@self-hosted-v3-testing.iam: . role
"spacelift-backend@self-hosted-v3-testing.iam" cannot be dropped because
some objects depend on it Details: privileges for database spacelift│
261 objects in database spacelift., invalid
```